### ISSUE TITLE
Skip Checking History

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/action-conventional-commits#2]
We had some unfortnate cicumstances with the conventional commits in the UbiquiBot repository and now its always failing. 

Fix to only check the latest commit message instead of the entire branch history.

**Comment by PhantomCracker** [comment]
@pavlovcik i see that this is a urgent issue, i can try to do it until Sunday, or if everything goes fine, today

**Comment by PhantomCracker** [comment]
Hello @pavlovcik ,
I have some questions regarding this issue: I see that at this point we check all the commits from a specific branch; by this issue do you mean that **we need to check only the latest commits (or only the last one if there is one commit - like in this example https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5443303678) instead of all branch commits (or this - https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5443304076/jobs/9899664781)?** 
I also see that the commits from another branch (e.g development), (when you create a new branch, you usually take the changes that are made in that specific branch - in my case for example, i have branches #1 and #3 that are based on master branch) are not checked.

**Comment by 0x4007** [comment]
> we need to check only the latest commits (or only the last one if there is one commit - like in this example https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5443303678) instead of all branch commits

Just check the latest commit if it passes.

**Comment by PhantomCracker** [comment]
If these are the requirements, then we need to trigger the GitHub action "Conventional Commits" only on push:
<img width="524" alt="Screenshot 2023-07-04 at 10 35 39" src="https://github.com/ubiquity/action-conventional-commits/assets/5438246/00697019-f7a3-47f4-855e-94835ffe70a6">

In this case, the pull request should be made on this project: https://github.com/ubiquity/ubiquity-dollar
Is ok for you if I will create the PR there and link with this issue? I am not sure if is possible to really link them with #number_of_issue 
If you have any other solution to solve this, please let me know @pavlovcik .

**Comment by 0x4007** [comment]
Yes I've seen cross repository pull request/issue links. Here is an example of how to do it https://github.com/ubiquity/devpool-directory/pull/660
